--[[
	ExtraObjects.lua
	ModuleScript: ReplicatedStorage.ExtraObjects

	More objects across every category, including a big batch of animals.
	Each has a low-poly model in ObjectModels (see Models/Extra*.lua,
	Models/MoreAnimals.lua, Models/Places.lua and Models/Records.lua). RoundGenerator pairs these up with
	each other and with the original objects to make lots of extra rounds,
	using each object's `fact` in the answer text.

	height is in meters (real-world size; Brainrot sizes are made up).
]]

return {
	{ name = "Labrador Dog", icon = "🐕", height = 0.6, category = "Animals", fact = "Labradors stand about 55-62 cm at the shoulder." },
	{ name = "Horse", icon = "🐴", height = 1.6, category = "Animals", fact = "Horses are measured in 'hands' -- a 16-hand horse is about 1.6 m at the withers." },
	{ name = "Dairy Cow", icon = "🐄", height = 1.4, category = "Animals", fact = "A dairy cow stands roughly 1.4 m at the shoulder and can weigh 600 kg." },
	{ name = "Sheep", icon = "🐑", height = 0.8, category = "Animals", fact = "A sheep stands around 80 cm at the shoulder." },
	{ name = "Pig", icon = "🐖", height = 0.9, category = "Animals", fact = "Domestic pigs are about 90 cm tall at the shoulder." },
	{ name = "Rabbit", icon = "🐇", height = 0.25, category = "Animals", fact = "Rabbits are only about 25 cm tall, ears not included." },
	{ name = "White-tailed Deer", icon = "🦌", height = 1.1, category = "Animals", fact = "A white-tailed deer stands about 1.1 m at the shoulder." },
	{ name = "Lion", icon = "🦁", height = 1.2, category = "Animals", fact = "Male lions stand about 1.2 m at the shoulder." },
	{ name = "Plains Zebra", icon = "🦓", height = 1.4, category = "Animals", fact = "A plains zebra stands about 1.4 m at the shoulder." },
	{ name = "Dromedary Camel", icon = "🐪", height = 2.1, category = "Animals", fact = "A dromedary stands around 2.1 m tall at the top of its hump." },
	{ name = "Hippopotamus", icon = "🦛", height = 1.5, category = "Animals", fact = "Hippos are only about 1.5 m tall but can weigh over 1,500 kg." },
	{ name = "White Rhinoceros", icon = "🦏", height = 1.8, category = "Animals", fact = "White rhinos stand about 1.8 m at the shoulder." },
	{ name = "Polar Bear", icon = "🐻‍❄️", height = 1.6, category = "Animals", fact = "A polar bear stands about 1.6 m at the shoulder on all fours." },
	{ name = "Giant Panda", icon = "🐼", height = 0.9, category = "Animals", fact = "Giant pandas are about 90 cm tall at the shoulder on all fours." },
	{ name = "Mountain Gorilla", icon = "🦍", height = 1.7, category = "Animals", fact = "A standing male gorilla is about 1.7 m tall." },
	{ name = "Saltwater Crocodile", icon = "🐊", height = 5, category = "Animals", fact = "Saltwater crocodiles are the largest living reptiles, reaching about 5 m." },
	{ name = "Great White Shark", icon = "🦈", height = 4.6, category = "Animals", fact = "Great whites average about 4.6 m long." },
	{ name = "Bottlenose Dolphin", icon = "🐬", height = 2.7, category = "Animals", fact = "Bottlenose dolphins are about 2.7 m long." },
	{ name = "Orca", icon = "🐋", height = 7, category = "Animals", fact = "Orcas can grow to about 7 m long." },
	{ name = "Bald Eagle", icon = "🦅", height = 0.9, category = "Animals", fact = "A bald eagle stands about 90 cm tall." },
	{ name = "Giant Tortoise", icon = "🐢", height = 1.2, category = "Animals", fact = "Giant tortoises can have shells over 1.2 m long." },
	{ name = "Tyrannosaurus Rex", icon = "🦖", height = 12, category = "Animals", fact = "T. rex was about 12 m long from nose to tail." },
	{ name = "Common Frog", icon = "🐸", height = 0.08, category = "Animals", fact = "A common frog is only around 8 cm long." },
	{ name = "Golden Hamster", icon = "🐹", height = 0.15, category = "Animals", fact = "A golden hamster is about 15 cm long." },
	{ name = "Leaning Tower of Pisa", icon = "🗼", height = 56, category = "Landmarks", fact = "The Leaning Tower of Pisa is about 56 m tall and leans about 4 degrees." },
	{ name = "Taj Mahal", icon = "🕌", height = 73, category = "Landmarks", fact = "The Taj Mahal's dome tops out about 73 m above its platform." },
	{ name = "Colosseum", icon = "🏟️", height = 188, category = "Landmarks", fact = "The Colosseum is about 188 m across, and could seat around 50,000 people." },
	{ name = "Sydney Opera House", icon = "🎭", height = 183, category = "Landmarks", fact = "The Sydney Opera House is about 183 m long." },
	{ name = "CN Tower", icon = "🗼", height = 553, category = "Landmarks", fact = "Toronto's CN Tower is 553 m tall." },
	{ name = "Empire State Building", icon = "🏙️", height = 443, category = "Landmarks", fact = "The Empire State Building is 443 m to the tip of its antenna." },
	{ name = "Space Needle", icon = "🛰️", height = 184, category = "Landmarks", fact = "Seattle's Space Needle is 184 m tall." },
	{ name = "Washington Monument", icon = "🗿", height = 169, category = "Landmarks", fact = "The Washington Monument is about 169 m tall." },
	{ name = "Arc de Triomphe", icon = "🏛️", height = 50, category = "Landmarks", fact = "The Arc de Triomphe is about 50 m tall." },
	{ name = "Christ the Redeemer", icon = "✝️", height = 38, category = "Landmarks", fact = "Christ the Redeemer is about 38 m tall including its pedestal." },
	{ name = "Stonehenge", icon = "🪨", height = 30, category = "Landmarks", fact = "Stonehenge's outer stone circle is about 30 m across." },
	{ name = "Moai Statue", icon = "🗿", height = 4, category = "Landmarks", fact = "A typical Easter Island moai is around 4 m tall." },
	{ name = "Great Sphinx", icon = "🦁", height = 73, category = "Landmarks", fact = "The Great Sphinx of Giza is about 73 m long." },
	{ name = "Parthenon", icon = "🏛️", height = 70, category = "Landmarks", fact = "The Parthenon in Athens is about 70 m long." },
	{ name = "Petronas Towers", icon = "🏢", height = 452, category = "Landmarks", fact = "The Petronas Twin Towers in Kuala Lumpur are 452 m tall." },
	{ name = "Tokyo Skytree", icon = "📡", height = 634, category = "Landmarks", fact = "Tokyo Skytree is 634 m tall, the tallest tower in the world." },
	{ name = "Mount Fuji", icon = "🗻", height = 3776, category = "Landmarks", fact = "Mount Fuji, Japan's highest peak, is 3,776 m." },
	{ name = "Matterhorn", icon = "⛰️", height = 4478, category = "Landmarks", fact = "The Matterhorn rises 4,478 m in the Alps." },
	{ name = "Golden Gate Bridge", icon = "🌉", height = 2737, category = "Landmarks", fact = "The Golden Gate Bridge is about 2,737 m long." },
	{ name = "Tower Bridge", icon = "🌉", height = 244, category = "Landmarks", fact = "London's Tower Bridge is about 244 m long." },
	{ name = "Pencil", icon = "✏️", height = 0.19, category = "Everyday Objects", fact = "A new pencil is about 19 cm long." },
	{ name = "Banana", icon = "🍌", height = 0.2, category = "Everyday Objects", fact = "A banana is about 20 cm long." },
	{ name = "Apple", icon = "🍎", height = 0.08, category = "Everyday Objects", fact = "An apple is about 8 cm across." },
	{ name = "Soccer Ball", icon = "⚽", height = 0.22, category = "Everyday Objects", fact = "A size 5 soccer ball is about 22 cm across." },
	{ name = "Bowling Pin", icon = "🎳", height = 0.38, category = "Everyday Objects", fact = "A ten-pin bowling pin is 38 cm tall." },
	{ name = "Acoustic Guitar", icon = "🎸", height = 1.0, category = "Everyday Objects", fact = "A full-size acoustic guitar is about 1 m long." },
	{ name = "Office Chair", icon = "💺", height = 1.0, category = "Everyday Objects", fact = "An office chair is roughly 1 m tall." },
	{ name = "Bicycle", icon = "🚲", height = 1.1, category = "Everyday Objects", fact = "A typical adult bicycle is about 1.1 m tall." },
	{ name = "Traffic Cone", icon = "🚧", height = 0.7, category = "Everyday Objects", fact = "A standard traffic cone is about 70 cm tall." },
	{ name = "Fire Hydrant", icon = "🧯", height = 0.75, category = "Everyday Objects", fact = "A fire hydrant is about 75 cm tall." },
	{ name = "Mailbox", icon = "📮", height = 1.2, category = "Everyday Objects", fact = "A street mailbox is about 1.2 m tall." },
	{ name = "Stop Sign", icon = "🛑", height = 2.1, category = "Everyday Objects", fact = "A stop sign on its post stands about 2.1 m tall." },
	{ name = "Street Lamp", icon = "💡", height = 5, category = "Everyday Objects", fact = "A street lamp is about 5 m tall." },
	{ name = "Ladder", icon = "🪜", height = 2, category = "Everyday Objects", fact = "A household stepladder is about 2 m tall." },
	{ name = "Umbrella", icon = "☂️", height = 0.9, category = "Everyday Objects", fact = "An open umbrella is about 90 cm tall." },
	{ name = "Toothbrush", icon = "🪥", height = 0.19, category = "Everyday Objects", fact = "A toothbrush is about 19 cm long." },
	{ name = "Laptop", icon = "💻", height = 0.33, category = "Everyday Objects", fact = "A 14-inch laptop is about 33 cm wide." },
	{ name = "Skateboard", icon = "🛹", height = 0.8, category = "Everyday Objects", fact = "A skateboard deck is about 80 cm long." },
	{ name = "Surfboard", icon = "🏄", height = 1.9, category = "Everyday Objects", fact = "A shortboard surfboard is about 1.9 m long." },
	{ name = "Single Bed", icon = "🛏️", height = 1.9, category = "Everyday Objects", fact = "A single bed is about 1.9 m long." },
	{ name = "Washing Machine", icon = "🧺", height = 0.85, category = "Everyday Objects", fact = "A washing machine is about 85 cm tall." },
	{ name = "Microwave Oven", icon = "🍲", height = 0.3, category = "Everyday Objects", fact = "A microwave oven is about 30 cm tall." },
	{ name = "Flat-Screen TV", icon = "📺", height = 0.65, category = "Everyday Objects", fact = "A 55-inch TV is about 65 cm tall." },
	{ name = "Candle", icon = "🕯️", height = 0.18, category = "Everyday Objects", fact = "A pillar candle is about 18 cm tall." },
	{ name = "Light Bulb", icon = "💡", height = 0.11, category = "Everyday Objects", fact = "A standard light bulb is about 11 cm tall." },
	{ name = "Pumpkin", icon = "🎃", height = 0.3, category = "Everyday Objects", fact = "A carving pumpkin is about 30 cm tall." },
	{ name = "Sedan Car", icon = "🚗", height = 4.7, category = "Everyday Objects", fact = "A family sedan is about 4.7 m long." },
	{ name = "School Bus", icon = "🚌", height = 10.6, category = "Everyday Objects", fact = "A full-size school bus is about 10.6 m long." },
	{ name = "Shipping Container", icon = "📦", height = 6.1, category = "Everyday Objects", fact = "A standard 20-foot shipping container is 6.1 m long." },
	{ name = "Telephone Booth", icon = "📞", height = 2.5, category = "Everyday Objects", fact = "A classic red phone box is about 2.5 m tall." },
	{ name = "Uranus", icon = "🔵", height = 50724000, category = "Space", fact = "Uranus is about 50,724 km across." },
	{ name = "Pluto", icon = "⚪", height = 2377000, category = "Space", fact = "Pluto is about 2,377 km across -- smaller than Earth's Moon." },
	{ name = "Ceres", icon = "🪨", height = 939000, category = "Space", fact = "Ceres, the largest object in the asteroid belt, is about 939 km across." },
	{ name = "Ganymede", icon = "🌑", height = 5268000, category = "Space", fact = "Ganymede, Jupiter's moon, is about 5,268 km across -- bigger than Mercury." },
	{ name = "Titan", icon = "🟠", height = 5150000, category = "Space", fact = "Titan, Saturn's largest moon, is about 5,150 km across." },
	{ name = "Io", icon = "🟡", height = 3643000, category = "Space", fact = "Io, the most volcanic body in the Solar System, is about 3,643 km across." },
	{ name = "Phobos", icon = "🪨", height = 22200, category = "Space", fact = "Phobos, a moon of Mars, is only about 22 km across." },
	{ name = "Halley's Comet", icon = "☄️", height = 15000, category = "Space", fact = "The nucleus of Halley's Comet is about 15 km long." },
	{ name = "International Space Station", icon = "🛰️", height = 109, category = "Space", fact = "The ISS is about 109 m across, roughly a football field." },
	{ name = "Hubble Space Telescope", icon = "🔭", height = 13.2, category = "Space", fact = "The Hubble Space Telescope is 13.2 m long." },
	{ name = "Saturn V Rocket", icon = "🚀", height = 110.6, category = "Space", fact = "The Saturn V Moon rocket stood 110.6 m tall." },
	{ name = "Falcon 9 Rocket", icon = "🚀", height = 70, category = "Space", fact = "A SpaceX Falcon 9 is about 70 m tall." },
	{ name = "Sputnik 1", icon = "🛰️", height = 0.58, category = "Space", fact = "Sputnik 1, the first satellite, was only 58 cm across." },
	{ name = "Apollo Lunar Module", icon = "🌕", height = 7, category = "Space", fact = "The Apollo Lunar Module was about 7 m tall with its legs extended." },
	{ name = "Bobrito Bandito", icon = "🦫", height = 1.6, category = "Brainrot", fact = "A beaver bandit with a mask and a very serious hat." },
	{ name = "Frigo Camelo", icon = "🐪", height = 3.2, category = "Brainrot", fact = "A camel with a fridge strapped on -- stays cool in the desert." },
	{ name = "Glorbo Fruttodrillo", icon = "🐊", height = 7, category = "Brainrot", fact = "A crocodile covered in fruit, snack and predator in one." },
	{ name = "Tric Trac Baraboom", icon = "💥", height = 3.8, category = "Brainrot", fact = "A walking firecracker with legs and a bad attitude." },
	{ name = "Boneca Ambalabu", icon = "🛞", height = 1.3, category = "Brainrot", fact = "A doll on a tire. Nobody knows why." },
	{ name = "Bombombini Gusini", icon = "🪿", height = 2.5, category = "Brainrot", fact = "A goose with jet engines for wings." },
	{ name = "Orcalero Orcala", icon = "🐋", height = 9, category = "Brainrot", fact = "A giant orca that walks around on legs." },
	{ name = "Gorillo Subwoofero", icon = "🦍", height = 3.6, category = "Brainrot", fact = "A gorilla with speakers for fists. Bass boosted." },
	{ name = "Elefanto Cocofanto", icon = "🐘", height = 4.8, category = "Brainrot", fact = "An elephant with a coconut for a body." },
	{ name = "Burbaloni Luliloli", icon = "🐌", height = 2, category = "Brainrot", fact = "A coconut-shelled snail with perfect hair." },
	{ name = "Pot Hotspot", icon = "🍲", height = 0.9, category = "Brainrot", fact = "A talking cooking pot that is always on the boil." },
	{ name = "Piccione Macchina", icon = "🐦", height = 2.8, category = "Brainrot", fact = "A pigeon that is also a car." },
	{ name = "Scary Verity", icon = "💀", height = 2.7, category = "Brainrot", fact = "A bony, grinning Verity that stands about 2.7 m tall. Don't look behind you." },

	-- More animals (models in Models/MoreAnimals.lua).
	{ name = "Chihuahua", icon = "🐕", height = 0.2, category = "Animals", fact = "Chihuahuas are the smallest dog breed, only about 20 cm tall at the shoulder." },
	{ name = "Great Dane", icon = "🐕", height = 0.8, category = "Animals", fact = "Great Danes stand about 80 cm at the shoulder -- one of the tallest dog breeds." },
	{ name = "German Shepherd", icon = "🐕", height = 0.6, category = "Animals", fact = "German Shepherds stand about 60 cm at the shoulder." },
	{ name = "Dachshund", icon = "🌭", height = 0.22, category = "Animals", fact = "Dachshunds are only about 22 cm tall, but much longer than they are tall." },
	{ name = "Corgi", icon = "🐕", height = 0.28, category = "Animals", fact = "Corgis stand only about 28 cm tall on their short legs." },
	{ name = "Gray Wolf", icon = "🐺", height = 0.8, category = "Animals", fact = "Gray wolves stand about 80 cm at the shoulder." },
	{ name = "Red Fox", icon = "🦊", height = 0.4, category = "Animals", fact = "A red fox stands about 40 cm at the shoulder." },
	{ name = "Arctic Fox", icon = "🦊", height = 0.3, category = "Animals", fact = "Arctic foxes are small: about 30 cm tall at the shoulder." },
	{ name = "Coyote", icon = "🐺", height = 0.6, category = "Animals", fact = "Coyotes stand about 60 cm at the shoulder." },
	{ name = "Bengal Tiger", icon = "🐅", height = 1, category = "Animals", fact = "Bengal tigers stand about 1 m tall at the shoulder." },
	{ name = "Leopard", icon = "🐆", height = 0.7, category = "Animals", fact = "Leopards stand about 70 cm at the shoulder." },
	{ name = "Cheetah", icon = "🐆", height = 0.8, category = "Animals", fact = "Cheetahs stand about 80 cm at the shoulder, with long legs built for speed." },
	{ name = "Snow Leopard", icon = "🐆", height = 0.6, category = "Animals", fact = "Snow leopards stand about 60 cm at the shoulder." },
	{ name = "Eurasian Lynx", icon = "🐈", height = 0.65, category = "Animals", fact = "A Eurasian lynx stands about 65 cm at the shoulder." },
	{ name = "American Black Bear", icon = "🐻", height = 0.9, category = "Animals", fact = "American black bears stand about 90 cm at the shoulder on all fours." },
	{ name = "Moose", icon = "🫎", height = 1.9, category = "Animals", fact = "Moose are the tallest deer, standing about 1.9 m at the shoulder." },
	{ name = "Elk", icon = "🦌", height = 1.5, category = "Animals", fact = "Elk stand about 1.5 m tall at the shoulder." },
	{ name = "Reindeer", icon = "🦌", height = 1.1, category = "Animals", fact = "Reindeer stand about 1.1 m at the shoulder." },
	{ name = "American Bison", icon = "🦬", height = 1.9, category = "Animals", fact = "American bison stand up to about 1.9 m at the top of their shoulder hump." },
	{ name = "Water Buffalo", icon = "🐃", height = 1.7, category = "Animals", fact = "Water buffalo stand about 1.7 m at the shoulder." },
	{ name = "Yak", icon = "🐂", height = 1.7, category = "Animals", fact = "Wild yaks stand about 1.7 m at the shoulder." },
	{ name = "Llama", icon = "🦙", height = 1.15, category = "Animals", fact = "Llamas stand about 1.15 m at the shoulder -- their heads reach about 1.8 m." },
	{ name = "Alpaca", icon = "🦙", height = 0.9, category = "Animals", fact = "Alpacas stand about 90 cm at the shoulder." },
	{ name = "Goat", icon = "🐐", height = 0.8, category = "Animals", fact = "A domestic goat stands about 80 cm at the shoulder." },
	{ name = "Donkey", icon = "🫏", height = 1.2, category = "Animals", fact = "Donkeys stand about 1.2 m at the shoulder." },
	{ name = "Shetland Pony", icon = "🐴", height = 1, category = "Animals", fact = "Shetland ponies are no taller than about 1 m at the shoulder." },
	{ name = "Clydesdale Horse", icon = "🐴", height = 1.8, category = "Animals", fact = "Clydesdales are huge horses, about 1.8 m tall at the shoulder." },
	{ name = "Okapi", icon = "🦓", height = 1.5, category = "Animals", fact = "Okapis stand about 1.5 m at the shoulder -- they're the giraffe's closest relative." },
	{ name = "Blue Wildebeest", icon = "🐃", height = 1.3, category = "Animals", fact = "Blue wildebeest stand about 1.3 m at the shoulder." },
	{ name = "Thomson's Gazelle", icon = "🦌", height = 0.65, category = "Animals", fact = "Thomson's gazelles stand about 65 cm at the shoulder." },
	{ name = "Warthog", icon = "🐗", height = 0.75, category = "Animals", fact = "Warthogs stand about 75 cm at the shoulder." },
	{ name = "Wild Boar", icon = "🐗", height = 0.9, category = "Animals", fact = "Wild boars stand about 90 cm at the shoulder." },
	{ name = "Malayan Tapir", icon = "🐖", height = 1, category = "Animals", fact = "Malayan tapirs stand about 1 m at the shoulder." },
	{ name = "Capybara", icon = "🐹", height = 0.6, category = "Animals", fact = "Capybaras are the biggest rodents, about 60 cm tall at the shoulder." },
	{ name = "Woolly Mammoth", icon = "🦣", height = 3.4, category = "Animals", fact = "Woolly mammoths stood about 3.4 m at the shoulder -- about as tall as an African elephant." },
	{ name = "Asian Elephant", icon = "🐘", height = 2.7, category = "Animals", fact = "Asian elephants stand about 2.7 m at the shoulder." },
	{ name = "Giant Anteater", icon = "🐜", height = 0.6, category = "Animals", fact = "Giant anteaters stand about 60 cm at the shoulder, but are 2 m long nose to tail." },
	{ name = "Ring-tailed Lemur", icon = "🐒", height = 0.2, category = "Animals", fact = "A ring-tailed lemur's body stands only about 20 cm tall on all fours." },
	{ name = "Raccoon", icon = "🦝", height = 0.3, category = "Animals", fact = "Raccoons stand about 30 cm at the shoulder." },
	{ name = "Striped Skunk", icon = "🦨", height = 0.2, category = "Animals", fact = "A striped skunk stands only about 20 cm tall." },
	{ name = "European Badger", icon = "🦡", height = 0.3, category = "Animals", fact = "Badgers stand about 30 cm at the shoulder." },
	{ name = "Hedgehog", icon = "🦔", height = 0.2, category = "Animals", fact = "Hedgehogs are about 20 cm long." },
	{ name = "Nine-banded Armadillo", icon = "🐾", height = 0.4, category = "Animals", fact = "A nine-banded armadillo's body is about 40 cm long, not counting its tail." },
	{ name = "North American Beaver", icon = "🦫", height = 1, category = "Animals", fact = "Beavers are about 1 m long, including their flat tail." },
	{ name = "Red Squirrel", icon = "🐿️", height = 0.2, category = "Animals", fact = "A red squirrel's body is about 20 cm long, plus a bushy tail." },
	{ name = "Guinea Pig", icon = "🐹", height = 0.25, category = "Animals", fact = "Guinea pigs are about 25 cm long." },
	{ name = "House Mouse", icon = "🐁", height = 0.08, category = "Animals", fact = "A house mouse's body is about 8 cm long, not counting its tail." },
	{ name = "Brown Rat", icon = "🐀", height = 0.22, category = "Animals", fact = "A brown rat's body is about 22 cm long, plus a tail about as long." },
	{ name = "Ferret", icon = "🐾", height = 0.4, category = "Animals", fact = "Ferrets are about 40 cm long, not counting their tail." },
	{ name = "Meerkat", icon = "🐾", height = 0.3, category = "Animals", fact = "A meerkat standing on lookout is about 30 cm tall." },
	{ name = "Koala", icon = "🐨", height = 0.75, category = "Animals", fact = "Koalas are about 75 cm tall sitting up in a tree." },
	{ name = "Red Kangaroo", icon = "🦘", height = 1.8, category = "Animals", fact = "A big male red kangaroo stands about 1.8 m tall." },
	{ name = "Chimpanzee", icon = "🐒", height = 1.2, category = "Animals", fact = "A standing chimpanzee is about 1.2 m tall." },
	{ name = "Bornean Orangutan", icon = "🦧", height = 1.4, category = "Animals", fact = "A standing male orangutan is about 1.4 m tall." },
	{ name = "Flamingo", icon = "🦩", height = 1.4, category = "Animals", fact = "Greater flamingos stand up to about 1.4 m tall." },
	{ name = "Peacock", icon = "🦚", height = 2.2, category = "Animals", fact = "A peacock is about 2.2 m long from beak to the tip of its train." },
	{ name = "Chicken", icon = "🐔", height = 0.4, category = "Animals", fact = "A chicken stands about 40 cm tall." },
	{ name = "Wild Turkey", icon = "🦃", height = 1, category = "Animals", fact = "A male wild turkey stands about 1 m tall when he fans his tail." },
	{ name = "Mallard Duck", icon = "🦆", height = 0.58, category = "Animals", fact = "Mallards are about 58 cm long from beak to tail." },
	{ name = "Mute Swan", icon = "🦢", height = 1.5, category = "Animals", fact = "Mute swans are about 1.5 m long from beak to tail." },
	{ name = "Canada Goose", icon = "🪿", height = 0.9, category = "Animals", fact = "Canada geese are about 90 cm long from beak to tail." },
	{ name = "Rock Pigeon", icon = "🐦", height = 0.32, category = "Animals", fact = "A city pigeon is about 32 cm long from beak to tail." },
	{ name = "American Crow", icon = "🐦‍⬛", height = 0.45, category = "Animals", fact = "American crows are about 45 cm long from beak to tail." },
	{ name = "Scarlet Macaw", icon = "🦜", height = 0.85, category = "Animals", fact = "Scarlet macaws are about 85 cm long -- over half of that is tail." },
	{ name = "Toco Toucan", icon = "🐦", height = 0.6, category = "Animals", fact = "Toco toucans are about 60 cm long, and their bill is a third of that." },
	{ name = "Great Horned Owl", icon = "🦉", height = 0.55, category = "Animals", fact = "Great horned owls stand about 55 cm tall." },
	{ name = "Ruby-throated Hummingbird", icon = "🐦", height = 0.08, category = "Animals", fact = "Ruby-throated hummingbirds are only about 8 cm long." },
	{ name = "Emu", icon = "🐦", height = 1.8, category = "Animals", fact = "Emus stand up to about 1.8 m tall." },
	{ name = "Southern Cassowary", icon = "🐦", height = 1.7, category = "Animals", fact = "Southern cassowaries stand about 1.7 m tall." },
	{ name = "Brown Kiwi", icon = "🥝", height = 0.4, category = "Animals", fact = "Brown kiwis stand about 40 cm tall." },
	{ name = "Atlantic Puffin", icon = "🐧", height = 0.3, category = "Animals", fact = "Atlantic puffins stand about 30 cm tall." },
	{ name = "Shoebill", icon = "🐦", height = 1.2, category = "Animals", fact = "Shoebills stand about 1.2 m tall." },
	{ name = "Secretary Bird", icon = "🐦", height = 1.3, category = "Animals", fact = "Secretary birds stand about 1.3 m tall on their long legs." },
	{ name = "White Stork", icon = "🐦", height = 1, category = "Animals", fact = "White storks stand about 1 m tall." },
	{ name = "Great Blue Heron", icon = "🐦", height = 1.2, category = "Animals", fact = "Great blue herons stand about 1.2 m tall." },
	{ name = "Andean Condor", icon = "🦅", height = 3.2, category = "Animals", fact = "Andean condors have wings about 3.2 m from tip to tip." },
	{ name = "Wandering Albatross", icon = "🐦", height = 3.1, category = "Animals", fact = "The wandering albatross has the longest wings of any bird, about 3.1 m tip to tip." },
	{ name = "Large Flying Fox", icon = "🦇", height = 1.5, category = "Animals", fact = "The large flying fox is a bat with wings about 1.5 m tip to tip." },
	{ name = "Humpback Whale", icon = "🐋", height = 15, category = "Animals", fact = "Humpback whales are about 15 m long." },
	{ name = "Sperm Whale", icon = "🐋", height = 16, category = "Animals", fact = "Male sperm whales are about 16 m long." },
	{ name = "Narwhal", icon = "🐋", height = 4.5, category = "Animals", fact = "Narwhals are about 4.5 m long, not counting the tusk." },
	{ name = "Beluga Whale", icon = "🐋", height = 4, category = "Animals", fact = "Beluga whales are about 4 m long." },
	{ name = "West Indian Manatee", icon = "🦭", height = 3, category = "Animals", fact = "West Indian manatees are about 3 m long." },
	{ name = "Walrus", icon = "🦭", height = 3, category = "Animals", fact = "A male walrus is about 3 m long." },
	{ name = "California Sea Lion", icon = "🦭", height = 2.2, category = "Animals", fact = "Male California sea lions are about 2.2 m long." },
	{ name = "Harbor Seal", icon = "🦭", height = 1.7, category = "Animals", fact = "Harbor seals are about 1.7 m long." },
	{ name = "Sea Otter", icon = "🦦", height = 1.2, category = "Animals", fact = "Sea otters are about 1.2 m long, tail included." },
	{ name = "Great Hammerhead", icon = "🦈", height = 4.5, category = "Animals", fact = "Great hammerhead sharks are about 4.5 m long." },
	{ name = "Whale Shark", icon = "🦈", height = 12, category = "Animals", fact = "Whale sharks are the biggest fish in the sea, about 12 m long." },
	{ name = "Giant Manta Ray", icon = "🐟", height = 7, category = "Animals", fact = "Giant manta rays can be about 7 m from wingtip to wingtip." },
	{ name = "Swordfish", icon = "🐟", height = 3, category = "Animals", fact = "Swordfish are about 3 m long, including their sword." },
	{ name = "Clownfish", icon = "🐠", height = 0.1, category = "Animals", fact = "Clownfish are only about 10 cm long." },
	{ name = "Goldfish", icon = "🐟", height = 0.15, category = "Animals", fact = "A pet goldfish is usually about 15 cm long." },
	{ name = "Atlantic Bluefin Tuna", icon = "🐟", height = 2.5, category = "Animals", fact = "Atlantic bluefin tuna are about 2.5 m long." },
	{ name = "Atlantic Salmon", icon = "🐟", height = 0.75, category = "Animals", fact = "Atlantic salmon are about 75 cm long." },
	{ name = "Common Octopus", icon = "🐙", height = 1, category = "Animals", fact = "A common octopus is about 1 m across with its arms spread." },
	{ name = "Giant Squid", icon = "🦑", height = 12, category = "Animals", fact = "Giant squid can be about 12 m long, including their two long tentacles." },
	{ name = "Moon Jellyfish", icon = "🪼", height = 0.3, category = "Animals", fact = "A moon jellyfish's bell is about 30 cm across." },
	{ name = "Seahorse", icon = "🐴", height = 0.15, category = "Animals", fact = "A common seahorse is about 15 cm tall." },
	{ name = "Common Starfish", icon = "⭐", height = 0.2, category = "Animals", fact = "A common starfish is about 20 cm across." },
	{ name = "American Lobster", icon = "🦞", height = 0.5, category = "Animals", fact = "An American lobster is about 50 cm long, claws not included." },
	{ name = "Japanese Spider Crab", icon = "🦀", height = 3.7, category = "Animals", fact = "Japanese spider crabs can be about 3.7 m across from leg tip to leg tip." },
	{ name = "Green Sea Turtle", icon = "🐢", height = 1.1, category = "Animals", fact = "A green sea turtle's shell is about 1.1 m long." },
	{ name = "Megalodon", icon = "🦈", height = 15, category = "Animals", fact = "The extinct megalodon shark was about 15 m long (scientists' best estimate)." },
	{ name = "Komodo Dragon", icon = "🦎", height = 2.6, category = "Animals", fact = "Komodo dragons are the biggest lizards, about 2.6 m long." },
	{ name = "Green Anaconda", icon = "🐍", height = 6, category = "Animals", fact = "Green anacondas can be about 6 m long." },
	{ name = "King Cobra", icon = "🐍", height = 4, category = "Animals", fact = "King cobras are the longest venomous snakes, about 4 m long." },
	{ name = "Rattlesnake", icon = "🐍", height = 1.2, category = "Animals", fact = "A western diamondback rattlesnake is about 1.2 m long." },
	{ name = "Green Iguana", icon = "🦎", height = 1.5, category = "Animals", fact = "Green iguanas are about 1.5 m long, mostly tail." },
	{ name = "Panther Chameleon", icon = "🦎", height = 0.45, category = "Animals", fact = "Panther chameleons are about 45 cm long, tail included." },
	{ name = "Leopard Gecko", icon = "🦎", height = 0.2, category = "Animals", fact = "Leopard geckos are about 20 cm long." },
	{ name = "American Alligator", icon = "🐊", height = 4, category = "Animals", fact = "A male American alligator is about 4 m long." },
	{ name = "Eastern Box Turtle", icon = "🐢", height = 0.15, category = "Animals", fact = "An eastern box turtle's shell is about 15 cm long." },
	{ name = "Axolotl", icon = "🦎", height = 0.23, category = "Animals", fact = "Axolotls are about 23 cm long." },
	{ name = "Strawberry Poison Frog", icon = "🐸", height = 0.02, category = "Animals", fact = "Strawberry poison frogs are tiny: only about 2 cm long." },
	{ name = "American Bullfrog", icon = "🐸", height = 0.15, category = "Animals", fact = "American bullfrogs are about 15 cm long." },
	{ name = "Honeybee", icon = "🐝", height = 0.015, category = "Animals", fact = "A worker honeybee is about 1.5 cm long." },
	{ name = "Ladybug", icon = "🐞", height = 0.008, category = "Animals", fact = "A ladybug is only about 8 mm long." },
	{ name = "Monarch Butterfly", icon = "🦋", height = 0.1, category = "Animals", fact = "Monarch butterflies have wings about 10 cm tip to tip." },
	{ name = "Black Garden Ant", icon = "🐜", height = 0.005, category = "Animals", fact = "A black garden ant worker is only about 5 mm long." },
	{ name = "Goliath Birdeater", icon = "🕷️", height = 0.28, category = "Animals", fact = "The Goliath birdeater tarantula has legs about 28 cm across." },
	{ name = "Emperor Scorpion", icon = "🦂", height = 0.2, category = "Animals", fact = "Emperor scorpions are about 20 cm long." },
	{ name = "Praying Mantis", icon = "🦗", height = 0.1, category = "Animals", fact = "A Chinese praying mantis is about 10 cm long." },
	{ name = "Emperor Dragonfly", icon = "🐉", height = 0.08, category = "Animals", fact = "Emperor dragonflies are about 8 cm long." },
	{ name = "Garden Snail", icon = "🐌", height = 0.04, category = "Animals", fact = "A garden snail stretches about 4 cm long when it crawls." },
	{ name = "Earthworm", icon = "🪱", height = 0.25, category = "Animals", fact = "A big nightcrawler earthworm is about 25 cm long." },
	{ name = "Atlas Moth", icon = "🦋", height = 0.25, category = "Animals", fact = "Atlas moths have wings about 25 cm tip to tip." },
	{ name = "Hercules Beetle", icon = "🪲", height = 0.17, category = "Animals", fact = "A male Hercules beetle is about 17 cm long, horn included." },
	{ name = "Grasshopper", icon = "🦗", height = 0.05, category = "Animals", fact = "A grasshopper is about 5 cm long." },
	{ name = "Triceratops", icon = "🦕", height = 9, category = "Animals", fact = "Triceratops was about 9 m long." },
	{ name = "Stegosaurus", icon = "🦕", height = 9, category = "Animals", fact = "Stegosaurus was about 9 m long, with plates down its back." },
	{ name = "Brachiosaurus", icon = "🦕", height = 12, category = "Animals", fact = "Brachiosaurus could raise its head about 12 m high." },
	{ name = "Velociraptor", icon = "🦖", height = 2, category = "Animals", fact = "Velociraptor was only about 2 m long, mostly tail -- about the size of a turkey." },
	{ name = "Spinosaurus", icon = "🦖", height = 15, category = "Animals", fact = "Spinosaurus was about 15 m long, even longer than T. rex." },
	{ name = "Pteranodon", icon = "🦅", height = 6, category = "Animals", fact = "Pteranodon had wings about 6 m from tip to tip." },

	-- Countries and continents (models in Models/Places.lua). Size is the
	-- widest straight-line span; the US is the lower 48 and France is mainland.
	{ name = "United States", icon = "🇺🇸", height = 4700000, category = "Countries", fact = "The lower 48 United States stretch about 4,700 km across at the widest." },
	{ name = "Canada", icon = "🇨🇦", height = 5600000, category = "Countries", fact = "Canada is about 5,600 km across at its widest -- the second-biggest country." },
	{ name = "Mexico", icon = "🇲🇽", height = 3300000, category = "Countries", fact = "Mexico stretches about 3,300 km from corner to corner." },
	{ name = "Brazil", icon = "🇧🇷", height = 4400000, category = "Countries", fact = "Brazil is about 4,400 km across -- the biggest country in South America." },
	{ name = "Argentina", icon = "🇦🇷", height = 3700000, category = "Countries", fact = "Argentina runs about 3,700 km from north to south." },
	{ name = "United Kingdom", icon = "🇬🇧", height = 980000, category = "Countries", fact = "The United Kingdom is about 980 km from top to bottom." },
	{ name = "France", icon = "🇫🇷", height = 1400000, category = "Countries", fact = "Mainland France is about 1,400 km across at its widest." },
	{ name = "Germany", icon = "🇩🇪", height = 890000, category = "Countries", fact = "Germany is about 890 km across at its widest." },
	{ name = "Italy", icon = "🇮🇹", height = 1200000, category = "Countries", fact = "Italy -- the boot -- is about 1,200 km from end to end." },
	{ name = "Spain", icon = "🇪🇸", height = 1100000, category = "Countries", fact = "Spain is about 1,100 km across at its widest." },
	{ name = "Russia", icon = "🇷🇺", height = 8100000, category = "Countries", fact = "Russia is about 8,100 km across in a straight line -- the biggest country on Earth." },
	{ name = "China", icon = "🇨🇳", height = 5000000, category = "Countries", fact = "China is about 5,000 km across at its widest." },
	{ name = "India", icon = "🇮🇳", height = 3100000, category = "Countries", fact = "India is about 3,100 km across at its widest." },
	{ name = "Japan", icon = "🇯🇵", height = 2000000, category = "Countries", fact = "Japan's islands stretch about 2,000 km from end to end." },
	{ name = "South Korea", icon = "🇰🇷", height = 500000, category = "Countries", fact = "South Korea is only about 500 km from top to bottom." },
	{ name = "Australia", icon = "🇦🇺", height = 4000000, category = "Countries", fact = "Australia is about 4,000 km across -- a country and a continent." },
	{ name = "New Zealand", icon = "🇳🇿", height = 1400000, category = "Countries", fact = "New Zealand's islands stretch about 1,400 km from end to end." },
	{ name = "Egypt", icon = "🇪🇬", height = 1600000, category = "Countries", fact = "Egypt is about 1,600 km across at its widest." },
	{ name = "South Africa", icon = "🇿🇦", height = 1800000, category = "Countries", fact = "South Africa is about 1,800 km across at its widest." },
	{ name = "Saudi Arabia", icon = "🇸🇦", height = 2300000, category = "Countries", fact = "Saudi Arabia is about 2,300 km across at its widest." },
	{ name = "Turkey", icon = "🇹🇷", height = 1700000, category = "Countries", fact = "Turkey is about 1,700 km from west to east." },
	{ name = "Indonesia", icon = "🇮🇩", height = 5300000, category = "Countries", fact = "Indonesia's thousands of islands stretch about 5,300 km from end to end." },
	{ name = "Nigeria", icon = "🇳🇬", height = 1500000, category = "Countries", fact = "Nigeria is about 1,500 km across at its widest." },
	{ name = "Africa", icon = "🌍", height = 8800000, category = "Countries", fact = "Africa is about 8,800 km across at its widest." },
	{ name = "Asia", icon = "🌏", height = 12800000, category = "Countries", fact = "Asia, the biggest continent, is about 12,800 km across at its widest." },
	{ name = "Europe", icon = "🌍", height = 5800000, category = "Countries", fact = "Europe is about 5,800 km across at its widest." },
	{ name = "North America", icon = "🌎", height = 10000000, category = "Countries", fact = "North America is about 10,000 km across at its widest." },
	{ name = "South America", icon = "🌎", height = 7600000, category = "Countries", fact = "South America is about 7,600 km from top to bottom." },
	{ name = "Antarctica", icon = "🧊", height = 5700000, category = "Countries", fact = "Antarctica is about 5,700 km across -- covered in ice." },

	-- CRAZY: record breakers -- the tiniest and biggest living things, prehistoric
	-- giants, huge machines, Earth's extremes and space giants (models in
	-- Models/Records.lua).
	{ name = "Flu Virus", icon = "🦠", height = 1e-07, category = "Crazy", fact = "A flu virus is only about 100 nanometres across -- about 700 would fit across a human hair." },
	{ name = "Bacteriophage", icon = "🦠", height = 2e-07, category = "Crazy", fact = "This virus looks like a tiny moon lander and is about 200 nanometres tall. It infects bacteria." },
	{ name = "E. coli Bacterium", icon = "🦠", height = 2e-06, category = "Crazy", fact = "An E. coli bacterium is about 2 micrometres long -- around 500 in a row would make a millimetre." },
	{ name = "Red Blood Cell", icon = "🩸", height = 7.5e-06, category = "Crazy", fact = "A red blood cell is about 7.5 micrometres across. You have about 25 trillion of them." },
	{ name = "Human Hair (width)", icon = "💇", height = 7e-05, category = "Crazy", fact = "A human hair is only about 70 micrometres wide." },
	{ name = "Dust Mite", icon = "🕷️", height = 0.00025, category = "Crazy", fact = "Dust mites are about a quarter of a millimetre long -- too small to see without a microscope." },
	{ name = "Fairyfly", icon = "🦟", height = 0.0002, category = "Crazy", fact = "Fairyflies are among the smallest insects on Earth, about 0.2 mm long." },
	{ name = "Tardigrade", icon = "🐻", height = 0.0005, category = "Crazy", fact = "Tardigrades (\"water bears\") are about half a millimetre long and can even survive in space." },
	{ name = "Grain of Sand", icon = "🏖️", height = 0.0005, category = "Crazy", fact = "A typical grain of sand is about half a millimetre across." },
	{ name = "Smallest Computer", icon = "💻", height = 0.0003, category = "Crazy", fact = "The Michigan Micro Mote is a working computer only about 0.3 mm across." },
	{ name = "Paedophryne Frog", icon = "🐸", height = 0.0077, category = "Crazy", fact = "Paedophryne amauensis, one of the world's smallest frogs, is under 8 mm long." },
	{ name = "Nano-Chameleon", icon = "🦎", height = 0.022, category = "Crazy", fact = "The nano-chameleon is about 2.2 cm long from nose to tail -- it fits on a fingertip." },
	{ name = "Pygmy Seahorse", icon = "🐴", height = 0.02, category = "Crazy", fact = "Pygmy seahorses are only about 2 cm tall and hide on sea fans." },
	{ name = "Bumblebee Bat", icon = "🦇", height = 0.03, category = "Crazy", fact = "The bumblebee bat's body is only about 3 cm long -- it's one of the smallest mammals." },
	{ name = "Etruscan Shrew", icon = "🐭", height = 0.04, category = "Crazy", fact = "The Etruscan shrew is about 4 cm long and weighs less than 2 grams." },
	{ name = "Bee Hummingbird", icon = "🐦", height = 0.055, category = "Crazy", fact = "The bee hummingbird is the world's smallest bird, about 5.5 cm long." },
	{ name = "Mouse Lemur", icon = "🐒", height = 0.09, category = "Crazy", fact = "Madame Berthe's mouse lemur, the smallest primate, has a body about 9 cm long." },
	{ name = "Pygmy Marmoset", icon = "🐒", height = 0.13, category = "Crazy", fact = "Pygmy marmosets, the smallest monkeys, have bodies about 13 cm long." },
	{ name = "Thumbelina the Horse", icon = "🐴", height = 0.43, category = "Crazy", fact = "Thumbelina, one of the smallest horses ever, stood about 43 cm tall." },
	{ name = "Hummingbird Egg", icon = "🥚", height = 0.013, category = "Crazy", fact = "A hummingbird egg is about 1.3 cm long -- the size of a jelly bean." },
	{ name = "Goliath Beetle", icon = "🪲", height = 0.11, category = "Crazy", fact = "Goliath beetles grow to about 11 cm long -- one of the heaviest insects." },
	{ name = "Goliath Frog", icon = "🐸", height = 0.32, category = "Crazy", fact = "The Goliath frog's body is about 32 cm long -- the biggest frog in the world." },
	{ name = "Giant Isopod", icon = "🦐", height = 0.36, category = "Crazy", fact = "Giant isopods, deep-sea cousins of woodlice, grow to about 36 cm long." },
	{ name = "Coconut Crab", icon = "🦀", height = 1, category = "Crazy", fact = "Coconut crabs have legs about 1 m across and can crack open coconuts." },
	{ name = "Ostrich Egg", icon = "🥚", height = 0.15, category = "Crazy", fact = "An ostrich egg is about 15 cm long -- the biggest egg of any living bird." },
	{ name = "Giant Clam", icon = "🐚", height = 1.2, category = "Crazy", fact = "Giant clams can be about 1.2 m across and live over 100 years." },
	{ name = "Ocean Sunfish", icon = "🐟", height = 1.8, category = "Crazy", fact = "Ocean sunfish are about 1.8 m long and can weigh over 1,000 kg." },
	{ name = "Chinese Giant Salamander", icon = "🦎", height = 1.8, category = "Crazy", fact = "The Chinese giant salamander can reach about 1.8 m long -- the biggest amphibian." },
	{ name = "Giant Tube Worm", icon = "🪱", height = 2.4, category = "Crazy", fact = "Giant tube worms near deep-sea hot vents grow up to about 2.4 m tall." },
	{ name = "Giant Pacific Octopus", icon = "🐙", height = 4.3, category = "Crazy", fact = "A giant Pacific octopus can be about 4.3 m across with its arms spread." },
	{ name = "Reticulated Python", icon = "🐍", height = 7, category = "Crazy", fact = "Reticulated pythons, the longest snakes alive, can reach about 7 m." },
	{ name = "Colossal Squid", icon = "🦑", height = 4.5, category = "Crazy", fact = "Colossal squid, the heaviest invertebrates, reach about 4.5 m long." },
	{ name = "Lion's Mane Jellyfish", icon = "🪼", height = 37, category = "Crazy", fact = "The biggest lion's mane jellyfish ever found was about 37 m long, tentacles included." },
	{ name = "Rafflesia", icon = "🌺", height = 1, category = "Crazy", fact = "Rafflesia is the biggest single flower, about 1 m across -- and it smells like rotting meat." },
	{ name = "Titan Arum", icon = "🌸", height = 3, category = "Crazy", fact = "The titan arum's flower spike can reach about 3 m tall. It's also called the corpse flower." },
	{ name = "Giant Water Lily Pad", icon = "🪷", height = 3, category = "Crazy", fact = "A Victoria water lily leaf can be about 3 m across -- strong enough to hold a small child." },
	{ name = "Coco de Mer Seed", icon = "🥥", height = 0.5, category = "Crazy", fact = "The coco de mer has the biggest seed in the world, about 50 cm long." },
	{ name = "Giant Kelp", icon = "🌿", height = 45, category = "Crazy", fact = "Giant kelp can grow about 45 m long -- sometimes half a metre in a day." },
	{ name = "General Sherman Tree", icon = "🌲", height = 84, category = "Crazy", fact = "General Sherman, the biggest tree on Earth by volume, is about 84 m tall." },
	{ name = "Hyperion Tree", icon = "🌲", height = 116, category = "Crazy", fact = "Hyperion, a coast redwood, is the tallest known tree at about 116 m." },
	{ name = "Argentinosaurus", icon = "🦕", height = 35, category = "Crazy", fact = "Argentinosaurus may have been about 35 m long -- one of the biggest dinosaurs." },
	{ name = "Titanoboa", icon = "🐍", height = 13, category = "Crazy", fact = "Titanoboa, a snake that lived 60 million years ago, was about 13 m long." },
	{ name = "Quetzalcoatlus", icon = "🦅", height = 10, category = "Crazy", fact = "Quetzalcoatlus, a giant flying reptile, had wings about 10 m across." },
	{ name = "Paraceratherium", icon = "🦏", height = 4.8, category = "Crazy", fact = "Paraceratherium, the biggest land mammal ever, stood about 4.8 m at the shoulder." },
	{ name = "Gigantopithecus", icon = "🦍", height = 3, category = "Crazy", fact = "Gigantopithecus, an extinct ape, may have stood about 3 m tall." },
	{ name = "Elephant Bird", icon = "🐦", height = 3, category = "Crazy", fact = "The extinct elephant bird of Madagascar stood about 3 m tall." },
	{ name = "Irish Elk", icon = "🦌", height = 2.1, category = "Crazy", fact = "The extinct Irish elk stood about 2.1 m at the shoulder, with antlers 3.6 m wide." },
	{ name = "Arthropleura", icon = "🐛", height = 2.6, category = "Crazy", fact = "Arthropleura, a prehistoric millipede, was about 2.6 m long." },
	{ name = "Meganeura", icon = "🦋", height = 0.7, category = "Crazy", fact = "Meganeura, a prehistoric dragonfly, had wings about 70 cm across." },
	{ name = "Sarcosuchus", icon = "🐊", height = 9.5, category = "Crazy", fact = "Sarcosuchus, the \"SuperCroc\", was about 9.5 m long." },
	{ name = "Basilosaurus", icon = "🐋", height = 18, category = "Crazy", fact = "Basilosaurus, an ancient whale with tiny back legs, was about 18 m long." },
	{ name = "Giant Moa", icon = "🐦", height = 3.6, category = "Crazy", fact = "The giant moa could stretch about 3.6 m tall -- taller than an elephant." },
	{ name = "Seawise Giant", icon = "🚢", height = 458, category = "Crazy", fact = "Seawise Giant, the longest ship ever built, was about 458 m long." },
	{ name = "Antonov An-225", icon = "✈️", height = 88, category = "Crazy", fact = "The Antonov An-225, the biggest plane ever flown, had wings about 88 m across." },
	{ name = "Hindenburg", icon = "🎈", height = 245, category = "Crazy", fact = "The Hindenburg airship was about 245 m long -- almost as long as the Titanic." },
	{ name = "Bagger 293", icon = "🏗️", height = 225, category = "Crazy", fact = "Bagger 293, a giant digging machine, is about 225 m long." },
	{ name = "BelAZ 75710", icon = "🚛", height = 20.6, category = "Crazy", fact = "The BelAZ 75710 dump truck is about 20.6 m long and can carry 450 tonnes." },
	{ name = "Starship Rocket", icon = "🚀", height = 121, category = "Crazy", fact = "SpaceX's Starship stacked on its booster is about 121 m tall." },
	{ name = "Kingda Ka", icon = "🎢", height = 139, category = "Crazy", fact = "Kingda Ka was a roller coaster about 139 m tall -- for years the tallest in the world." },
	{ name = "Ain Dubai", icon = "🎡", height = 250, category = "Crazy", fact = "Ain Dubai is the tallest Ferris wheel in the world, about 250 m tall." },
	{ name = "Statue of Unity", icon = "🗿", height = 182, category = "Crazy", fact = "The Statue of Unity in India is about 182 m tall -- the tallest statue in the world." },
	{ name = "Three Gorges Dam", icon = "🏞️", height = 2335, category = "Crazy", fact = "The Three Gorges Dam in China is about 2.3 km long." },
	{ name = "Large Hadron Collider", icon = "⚛️", height = 8600, category = "Crazy", fact = "The Large Hadron Collider's underground ring is about 8.6 km across." },
	{ name = "Peel P50", icon = "🚗", height = 1.37, category = "Crazy", fact = "The Peel P50 is the smallest car ever made for sale, about 1.37 m long." },
	{ name = "Mariana Trench", icon = "🌊", height = 10935, category = "Crazy", fact = "The Mariana Trench is about 11 km deep -- deeper than Mount Everest is tall." },
	{ name = "Mauna Kea", icon = "🌋", height = 10210, category = "Crazy", fact = "Measured from the sea floor, Mauna Kea is about 10.2 km tall -- taller than Everest." },
	{ name = "Angel Falls", icon = "💦", height = 979, category = "Crazy", fact = "Angel Falls in Venezuela is the tallest waterfall, about 979 m high." },
	{ name = "Grand Canyon", icon = "🏜️", height = 1800, category = "Crazy", fact = "The Grand Canyon is about 1.8 km deep." },
	{ name = "Sahara Desert", icon = "🐪", height = 4800, category = "Crazy", fact = "The Sahara is about 4,800 km across -- almost as big as the United States." },
	{ name = "Iceberg B-15", icon = "🧊", height = 295000, category = "Crazy", fact = "Iceberg B-15 was about 295 km long -- one of the biggest icebergs ever seen." },
	{ name = "Giant Hailstone", icon = "🧊", height = 0.2, category = "Crazy", fact = "The biggest hailstone measured in the US was about 20 cm across." },
	{ name = "Largest Raindrop", icon = "💧", height = 0.009, category = "Crazy", fact = "Raindrops can't get much bigger than about 9 mm before they break apart." },
	{ name = "Lightning Bolt", icon = "⚡", height = 5000, category = "Crazy", fact = "A typical lightning bolt is about 5 km long." },
	{ name = "Naica Giant Crystal", icon = "💎", height = 12, category = "Crazy", fact = "The biggest crystals in Mexico's Naica cave are about 12 m long." },
	{ name = "Cullinan Diamond", icon = "💎", height = 0.1, category = "Crazy", fact = "The Cullinan, the biggest diamond ever found, was about 10 cm long." },
	{ name = "Chicxulub Asteroid", icon = "☄️", height = 10000, category = "Crazy", fact = "The asteroid that wiped out the dinosaurs was about 10 km across." },
	{ name = "Neutron Star", icon = "⭐", height = 20000, category = "Crazy", fact = "A neutron star is only about 20 km across but heavier than the Sun." },
	{ name = "Olympus Mons", icon = "🌋", height = 22000, category = "Crazy", fact = "Olympus Mons on Mars is about 22 km tall -- about 2.5 times Mount Everest." },
	{ name = "Valles Marineris", icon = "🏜️", height = 4000000, category = "Crazy", fact = "Valles Marineris, a giant canyon on Mars, is about 4,000 km long." },
	{ name = "Vesta", icon = "🪨", height = 525000, category = "Crazy", fact = "Vesta, one of the biggest asteroids, is about 525 km across." },
	{ name = "Great Red Spot", icon = "🌀", height = 1.4e+07, category = "Crazy", fact = "Jupiter's Great Red Spot, a storm bigger than Earth, is about 14,000 km wide." },
	{ name = "Saturn's Rings", icon = "🪐", height = 2.7e+08, category = "Crazy", fact = "Saturn's main rings are about 270,000 km across, but only about 10 m thick in places." },
	{ name = "Sagittarius A*", icon = "🕳️", height = 2.4e+10, category = "Crazy", fact = "The black hole at the centre of our galaxy is about 24 million km across." },
	{ name = "Betelgeuse", icon = "🔴", height = 1e+12, category = "Crazy", fact = "Betelgeuse, a red supergiant star, is about 1 billion km across." },
	{ name = "UY Scuti", icon = "🔴", height = 1.3e+12, category = "Crazy", fact = "UY Scuti, one of the biggest known stars, is about 1.3 billion km across." },
	{ name = "TON 618", icon = "🕳️", height = 3.9e+14, category = "Crazy", fact = "TON 618, one of the biggest black holes known, is about 390 billion km across." },
	{ name = "Our Solar System", icon = "☀️", height = 9e+12, category = "Crazy", fact = "From the Sun out to Neptune's orbit, our solar system is about 9 billion km across." },
	{ name = "Milky Way", icon = "🌌", height = 9.46e+20, category = "Crazy", fact = "Our galaxy, the Milky Way, is about 100,000 light-years across." },
	{ name = "Andromeda Galaxy", icon = "🌌", height = 2.08e+21, category = "Crazy", fact = "The Andromeda Galaxy is about 220,000 light-years across." },
	{ name = "Blue Whale Heart", icon = "❤️", height = 1.5, category = "Crazy", fact = "A blue whale's heart is about 1.5 m long and weighs about 180 kg." },
	{ name = "Giraffe Tongue", icon = "👅", height = 0.5, category = "Crazy", fact = "A giraffe's tongue is about 50 cm long -- and dark purple." },
	{ name = "Narwhal Tusk", icon = "🦄", height = 3, category = "Crazy", fact = "A narwhal's tusk is really a tooth, and can grow about 3 m long." },
	{ name = "Giant Squid Eye", icon = "👁️", height = 0.27, category = "Crazy", fact = "Giant and colossal squid have the biggest eyes of any animal, about 27 cm across." },
	{ name = "T. rex Tooth", icon = "🦷", height = 0.3, category = "Crazy", fact = "The biggest T. rex teeth, root included, were about 30 cm long." },
	{ name = "Zeus the Tallest Dog", icon = "🐕", height = 1.12, category = "Crazy", fact = "Zeus, a Great Dane, stood about 1.12 m at the shoulder -- the tallest dog ever." },
	{ name = "Darius the Giant Rabbit", icon = "🐇", height = 1.29, category = "Crazy", fact = "Darius, the longest rabbit ever recorded, measured about 1.29 m." },
	{ name = "Newborn Panda", icon = "🐼", height = 0.15, category = "Crazy", fact = "A newborn giant panda is only about 15 cm long -- about 1/900th of its mum's weight." },
	{ name = "Newborn Blue Whale", icon = "🐋", height = 7, category = "Crazy", fact = "A blue whale is already about 7 m long when it's born." },
	{ name = "Asian Giant Hornet", icon = "🐝", height = 0.05, category = "Crazy", fact = "The Asian giant hornet, the biggest hornet, is about 5 cm long." },
	{ name = "Titan Beetle", icon = "🪲", height = 0.167, category = "Crazy", fact = "Titan beetles grow to about 16.7 cm long." },
}
