--[[
	ExtraObjects.lua
	ModuleScript: ReplicatedStorage.ExtraObjects

	100 more objects across every category. Each has a low-poly model in
	ObjectModels (see Models/Extra*.lua). RoundGenerator pairs these up with
	each other and with the original objects to make lots of extra rounds,
	using each object's `fact` in the answer text.

	height is in meters (real-world size; Brainrot sizes are made up).
]]

return {
	{ name = "Labrador Dog", icon = "🐕", height = 0.6, category = "Animals", fact = "Labradors stand about 55-62 cm at the shoulder." },
	{ name = "Horse", icon = "🐴", height = 1.6, category = "Animals", fact = "Horses are measured in 'hands' -- a 16-hand horse is about 1.6 m at the withers." },
	{ name = "Dairy Cow", icon = "🐄", height = 1.4, category = "Animals", fact = "A dairy cow stands roughly 1.4 m at the shoulder and can weigh 600 kg." },
	{ name = "Sheep", icon = "🐑", height = 0.8, category = "Animals", fact = "A sheep stands around 80 cm at the shoulder." },
	{ name = "Pig", icon = "🐖", height = 0.9, category = "Animals", fact = "Domestic pigs are about 90 cm tall at the shoulder." },
	{ name = "Rabbit", icon = "🐇", height = 0.25, category = "Animals", fact = "Rabbits are only about 25 cm tall, ears not included." },
	{ name = "White-tailed Deer", icon = "🦌", height = 1.1, category = "Animals", fact = "A white-tailed deer stands about 1.1 m at the shoulder." },
	{ name = "Lion", icon = "🦁", height = 1.2, category = "Animals", fact = "Male lions stand about 1.2 m at the shoulder." },
	{ name = "Plains Zebra", icon = "🦓", height = 1.4, category = "Animals", fact = "A plains zebra stands about 1.4 m at the shoulder." },
	{ name = "Dromedary Camel", icon = "🐪", height = 2.1, category = "Animals", fact = "A dromedary stands around 2.1 m tall at the top of its hump." },
	{ name = "Hippopotamus", icon = "🦛", height = 1.5, category = "Animals", fact = "Hippos are only about 1.5 m tall but can weigh over 1,500 kg." },
	{ name = "White Rhinoceros", icon = "🦏", height = 1.8, category = "Animals", fact = "White rhinos stand about 1.8 m at the shoulder." },
	{ name = "Polar Bear", icon = "🐻‍❄️", height = 1.6, category = "Animals", fact = "A polar bear stands about 1.6 m at the shoulder on all fours." },
	{ name = "Giant Panda", icon = "🐼", height = 0.9, category = "Animals", fact = "Giant pandas are about 90 cm tall at the shoulder on all fours." },
	{ name = "Mountain Gorilla", icon = "🦍", height = 1.7, category = "Animals", fact = "A standing male gorilla is about 1.7 m tall." },
	{ name = "Saltwater Crocodile", icon = "🐊", height = 5, category = "Animals", fact = "Saltwater crocodiles are the largest living reptiles, reaching about 5 m." },
	{ name = "Great White Shark", icon = "🦈", height = 4.6, category = "Animals", fact = "Great whites average about 4.6 m long." },
	{ name = "Bottlenose Dolphin", icon = "🐬", height = 2.7, category = "Animals", fact = "Bottlenose dolphins are about 2.7 m long." },
	{ name = "Orca", icon = "🐋", height = 7, category = "Animals", fact = "Orcas can grow to about 7 m long." },
	{ name = "Bald Eagle", icon = "🦅", height = 0.9, category = "Animals", fact = "A bald eagle stands about 90 cm tall." },
	{ name = "Giant Tortoise", icon = "🐢", height = 1.2, category = "Animals", fact = "Giant tortoises can have shells over 1.2 m long." },
	{ name = "Tyrannosaurus Rex", icon = "🦖", height = 12, category = "Animals", fact = "T. rex was about 12 m long from nose to tail." },
	{ name = "Common Frog", icon = "🐸", height = 0.08, category = "Animals", fact = "A common frog is only around 8 cm long." },
	{ name = "Golden Hamster", icon = "🐹", height = 0.15, category = "Animals", fact = "A golden hamster is about 15 cm long." },
	{ name = "Leaning Tower of Pisa", icon = "🗼", height = 56, category = "Landmarks", fact = "The Leaning Tower of Pisa is about 56 m tall and leans about 4 degrees." },
	{ name = "Taj Mahal", icon = "🕌", height = 73, category = "Landmarks", fact = "The Taj Mahal's dome tops out about 73 m above its platform." },
	{ name = "Colosseum", icon = "🏟️", height = 188, category = "Landmarks", fact = "The Colosseum is about 188 m across, and could seat around 50,000 people." },
	{ name = "Sydney Opera House", icon = "🎭", height = 183, category = "Landmarks", fact = "The Sydney Opera House is about 183 m long." },
	{ name = "CN Tower", icon = "🗼", height = 553, category = "Landmarks", fact = "Toronto's CN Tower is 553 m tall." },
	{ name = "Empire State Building", icon = "🏙️", height = 443, category = "Landmarks", fact = "The Empire State Building is 443 m to the tip of its antenna." },
	{ name = "Space Needle", icon = "🛰️", height = 184, category = "Landmarks", fact = "Seattle's Space Needle is 184 m tall." },
	{ name = "Washington Monument", icon = "🗿", height = 169, category = "Landmarks", fact = "The Washington Monument is about 169 m tall." },
	{ name = "Arc de Triomphe", icon = "🏛️", height = 50, category = "Landmarks", fact = "The Arc de Triomphe is about 50 m tall." },
	{ name = "Christ the Redeemer", icon = "✝️", height = 38, category = "Landmarks", fact = "Christ the Redeemer is about 38 m tall including its pedestal." },
	{ name = "Stonehenge", icon = "🪨", height = 30, category = "Landmarks", fact = "Stonehenge's outer stone circle is about 30 m across." },
	{ name = "Moai Statue", icon = "🗿", height = 4, category = "Landmarks", fact = "A typical Easter Island moai is around 4 m tall." },
	{ name = "Great Sphinx", icon = "🦁", height = 73, category = "Landmarks", fact = "The Great Sphinx of Giza is about 73 m long." },
	{ name = "Parthenon", icon = "🏛️", height = 70, category = "Landmarks", fact = "The Parthenon in Athens is about 70 m long." },
	{ name = "Petronas Towers", icon = "🏢", height = 452, category = "Landmarks", fact = "The Petronas Twin Towers in Kuala Lumpur are 452 m tall." },
	{ name = "Tokyo Skytree", icon = "📡", height = 634, category = "Landmarks", fact = "Tokyo Skytree is 634 m tall, the tallest tower in the world." },
	{ name = "Mount Fuji", icon = "🗻", height = 3776, category = "Landmarks", fact = "Mount Fuji, Japan's highest peak, is 3,776 m." },
	{ name = "Matterhorn", icon = "⛰️", height = 4478, category = "Landmarks", fact = "The Matterhorn rises 4,478 m in the Alps." },
	{ name = "Golden Gate Bridge", icon = "🌉", height = 2737, category = "Landmarks", fact = "The Golden Gate Bridge is about 2,737 m long." },
	{ name = "Tower Bridge", icon = "🌉", height = 244, category = "Landmarks", fact = "London's Tower Bridge is about 244 m long." },
	{ name = "Pencil", icon = "✏️", height = 0.19, category = "Everyday Objects", fact = "A new pencil is about 19 cm long." },
	{ name = "Banana", icon = "🍌", height = 0.2, category = "Everyday Objects", fact = "A banana is about 20 cm long." },
	{ name = "Apple", icon = "🍎", height = 0.08, category = "Everyday Objects", fact = "An apple is about 8 cm across." },
	{ name = "Soccer Ball", icon = "⚽", height = 0.22, category = "Everyday Objects", fact = "A size 5 soccer ball is about 22 cm across." },
	{ name = "Bowling Pin", icon = "🎳", height = 0.38, category = "Everyday Objects", fact = "A ten-pin bowling pin is 38 cm tall." },
	{ name = "Acoustic Guitar", icon = "🎸", height = 1.0, category = "Everyday Objects", fact = "A full-size acoustic guitar is about 1 m long." },
	{ name = "Office Chair", icon = "💺", height = 1.0, category = "Everyday Objects", fact = "An office chair is roughly 1 m tall." },
	{ name = "Bicycle", icon = "🚲", height = 1.1, category = "Everyday Objects", fact = "A typical adult bicycle is about 1.1 m tall." },
	{ name = "Traffic Cone", icon = "🚧", height = 0.7, category = "Everyday Objects", fact = "A standard traffic cone is about 70 cm tall." },
	{ name = "Fire Hydrant", icon = "🧯", height = 0.75, category = "Everyday Objects", fact = "A fire hydrant is about 75 cm tall." },
	{ name = "Mailbox", icon = "📮", height = 1.2, category = "Everyday Objects", fact = "A street mailbox is about 1.2 m tall." },
	{ name = "Stop Sign", icon = "🛑", height = 2.1, category = "Everyday Objects", fact = "A stop sign on its post stands about 2.1 m tall." },
	{ name = "Street Lamp", icon = "💡", height = 5, category = "Everyday Objects", fact = "A street lamp is about 5 m tall." },
	{ name = "Ladder", icon = "🪜", height = 2, category = "Everyday Objects", fact = "A household stepladder is about 2 m tall." },
	{ name = "Umbrella", icon = "☂️", height = 0.9, category = "Everyday Objects", fact = "An open umbrella is about 90 cm tall." },
	{ name = "Toothbrush", icon = "🪥", height = 0.19, category = "Everyday Objects", fact = "A toothbrush is about 19 cm long." },
	{ name = "Laptop", icon = "💻", height = 0.33, category = "Everyday Objects", fact = "A 14-inch laptop is about 33 cm wide." },
	{ name = "Skateboard", icon = "🛹", height = 0.8, category = "Everyday Objects", fact = "A skateboard deck is about 80 cm long." },
	{ name = "Surfboard", icon = "🏄", height = 1.9, category = "Everyday Objects", fact = "A shortboard surfboard is about 1.9 m long." },
	{ name = "Single Bed", icon = "🛏️", height = 1.9, category = "Everyday Objects", fact = "A single bed is about 1.9 m long." },
	{ name = "Washing Machine", icon = "🧺", height = 0.85, category = "Everyday Objects", fact = "A washing machine is about 85 cm tall." },
	{ name = "Microwave Oven", icon = "🍲", height = 0.3, category = "Everyday Objects", fact = "A microwave oven is about 30 cm tall." },
	{ name = "Flat-Screen TV", icon = "📺", height = 0.65, category = "Everyday Objects", fact = "A 55-inch TV is about 65 cm tall." },
	{ name = "Candle", icon = "🕯️", height = 0.18, category = "Everyday Objects", fact = "A pillar candle is about 18 cm tall." },
	{ name = "Light Bulb", icon = "💡", height = 0.11, category = "Everyday Objects", fact = "A standard light bulb is about 11 cm tall." },
	{ name = "Pumpkin", icon = "🎃", height = 0.3, category = "Everyday Objects", fact = "A carving pumpkin is about 30 cm tall." },
	{ name = "Sedan Car", icon = "🚗", height = 4.7, category = "Everyday Objects", fact = "A family sedan is about 4.7 m long." },
	{ name = "School Bus", icon = "🚌", height = 10.6, category = "Everyday Objects", fact = "A full-size school bus is about 10.6 m long." },
	{ name = "Shipping Container", icon = "📦", height = 6.1, category = "Everyday Objects", fact = "A standard 20-foot shipping container is 6.1 m long." },
	{ name = "Telephone Booth", icon = "📞", height = 2.5, category = "Everyday Objects", fact = "A classic red phone box is about 2.5 m tall." },
	{ name = "Uranus", icon = "🔵", height = 50724000, category = "Space", fact = "Uranus is about 50,724 km across." },
	{ name = "Pluto", icon = "⚪", height = 2377000, category = "Space", fact = "Pluto is about 2,377 km across -- smaller than Earth's Moon." },
	{ name = "Ceres", icon = "🪨", height = 939000, category = "Space", fact = "Ceres, the largest object in the asteroid belt, is about 939 km across." },
	{ name = "Ganymede", icon = "🌑", height = 5268000, category = "Space", fact = "Ganymede, Jupiter's moon, is about 5,268 km across -- bigger than Mercury." },
	{ name = "Titan", icon = "🟠", height = 5150000, category = "Space", fact = "Titan, Saturn's largest moon, is about 5,150 km across." },
	{ name = "Io", icon = "🟡", height = 3643000, category = "Space", fact = "Io, the most volcanic body in the Solar System, is about 3,643 km across." },
	{ name = "Phobos", icon = "🪨", height = 22200, category = "Space", fact = "Phobos, a moon of Mars, is only about 22 km across." },
	{ name = "Halley's Comet", icon = "☄️", height = 15000, category = "Space", fact = "The nucleus of Halley's Comet is about 15 km long." },
	{ name = "International Space Station", icon = "🛰️", height = 109, category = "Space", fact = "The ISS is about 109 m across, roughly a football field." },
	{ name = "Hubble Space Telescope", icon = "🔭", height = 13.2, category = "Space", fact = "The Hubble Space Telescope is 13.2 m long." },
	{ name = "Saturn V Rocket", icon = "🚀", height = 110.6, category = "Space", fact = "The Saturn V Moon rocket stood 110.6 m tall." },
	{ name = "Falcon 9 Rocket", icon = "🚀", height = 70, category = "Space", fact = "A SpaceX Falcon 9 is about 70 m tall." },
	{ name = "Sputnik 1", icon = "🛰️", height = 0.58, category = "Space", fact = "Sputnik 1, the first satellite, was only 58 cm across." },
	{ name = "Apollo Lunar Module", icon = "🌕", height = 7, category = "Space", fact = "The Apollo Lunar Module was about 7 m tall with its legs extended." },
	{ name = "Bobrito Bandito", icon = "🦫", height = 1.6, category = "Brainrot", fact = "A beaver bandit with a mask and a very serious hat." },
	{ name = "Frigo Camelo", icon = "🐪", height = 3.2, category = "Brainrot", fact = "A camel with a fridge strapped on -- stays cool in the desert." },
	{ name = "Glorbo Fruttodrillo", icon = "🐊", height = 7, category = "Brainrot", fact = "A crocodile covered in fruit, snack and predator in one." },
	{ name = "Tric Trac Baraboom", icon = "💥", height = 3.8, category = "Brainrot", fact = "A walking firecracker with legs and a bad attitude." },
	{ name = "Boneca Ambalabu", icon = "🛞", height = 1.3, category = "Brainrot", fact = "A doll on a tire. Nobody knows why." },
	{ name = "Bombombini Gusini", icon = "🪿", height = 2.5, category = "Brainrot", fact = "A goose with jet engines for wings." },
	{ name = "Orcalero Orcala", icon = "🐋", height = 9, category = "Brainrot", fact = "A giant orca that walks around on legs." },
	{ name = "Gorillo Subwoofero", icon = "🦍", height = 3.6, category = "Brainrot", fact = "A gorilla with speakers for fists. Bass boosted." },
	{ name = "Elefanto Cocofanto", icon = "🐘", height = 4.8, category = "Brainrot", fact = "An elephant with a coconut for a body." },
	{ name = "Burbaloni Luliloli", icon = "🐌", height = 2, category = "Brainrot", fact = "A coconut-shelled snail with perfect hair." },
	{ name = "Pot Hotspot", icon = "🍲", height = 0.9, category = "Brainrot", fact = "A talking cooking pot that is always on the boil." },
	{ name = "Piccione Macchina", icon = "🐦", height = 2.8, category = "Brainrot", fact = "A pigeon that is also a car." },
}
