--[[
	ScaleData.lua
	ModuleScript: ReplicatedStorage.ScaleData

	Each entry describes one "guess the scale" round. Heights are in meters
	(real-world), used purely for computing ratios -- the client never sees
	targetHeight until after it submits a guess. Each name has a matching
	low-poly model in ObjectModels; icons are used if a model is missing.
]]

local ScaleData = {}

ScaleData.Rounds = {
	{
		referenceName = "African Elephant",
		referenceIcon = "🐘",
		referenceHeight = 3.2,
		targetName = "Giraffe",
		targetIcon = "🦒",
		targetHeight = 5.5,
		category = "Animals",
		fact = "A giraffe can be over 5.5 meters tall, roughly 40% taller than an African elephant.",
	},
	{
		referenceName = "House Cat",
		referenceIcon = "🐈",
		referenceHeight = 0.25,
		targetName = "Grizzly Bear",
		targetIcon = "🐻",
		targetHeight = 2.5,
		category = "Animals",
		fact = "A standing grizzly bear can reach about 2.5 meters -- 10 times the height of a house cat.",
	},
	{
		referenceName = "Human (Average Adult)",
		referenceIcon = "🧍",
		referenceHeight = 1.7,
		targetName = "Blue Whale",
		targetIcon = "🐋",
		targetHeight = 25,
		category = "Animals",
		fact = "Blue whales can grow to around 25-30 meters, the largest animals ever known to have existed.",
	},
	{
		referenceName = "Emperor Penguin",
		referenceIcon = "🐧",
		referenceHeight = 1.1,
		targetName = "Ostrich",
		targetIcon = "🐦",
		targetHeight = 2.7,
		category = "Animals",
		fact = "Ostriches, the tallest living birds, can reach about 2.7 meters -- more than double an emperor penguin.",
	},
	{
		referenceName = "Statue of Liberty",
		referenceIcon = "🗽",
		referenceHeight = 46,
		targetName = "Great Pyramid of Giza",
		targetIcon = "🔺",
		targetHeight = 138,
		category = "Landmarks",
		fact = "The Great Pyramid of Giza originally stood about 146 meters tall -- roughly 3x the Statue of Liberty.",
	},
	{
		referenceName = "Statue of Liberty",
		referenceIcon = "🗽",
		referenceHeight = 46,
		targetName = "Eiffel Tower",
		targetIcon = "🗼",
		targetHeight = 330,
		category = "Landmarks",
		fact = "The Eiffel Tower is about 330 meters tall, over 7 times the height of the Statue of Liberty.",
	},
	{
		referenceName = "London Double-Decker Bus",
		referenceIcon = "🚌",
		referenceHeight = 4.4,
		targetName = "Big Ben Clock Tower",
		targetIcon = "🕰️",
		targetHeight = 96,
		category = "Landmarks",
		fact = "The Elizabeth Tower (Big Ben) stands about 96 meters tall -- roughly 22 double-decker buses stacked up.",
	},
	{
		referenceName = "Burj Khalifa",
		referenceIcon = "🏙️",
		referenceHeight = 828,
		targetName = "Mount Everest",
		targetIcon = "🏔️",
		targetHeight = 8849,
		category = "Landmarks",
		fact = "Mount Everest rises about 8,849 meters -- more than 10 times the height of the Burj Khalifa.",
	},
	{
		referenceName = "Soda Can",
		referenceIcon = "🥤",
		referenceHeight = 0.123,
		targetName = "Basketball Hoop",
		targetIcon = "🏀",
		targetHeight = 3.05,
		category = "Everyday Objects",
		fact = "A regulation basketball hoop is 3.05 meters (10 feet) high -- about 25 soda cans stacked.",
	},
	{
		referenceName = "A4 Sheet of Paper",
		referenceIcon = "📄",
		referenceHeight = 0.297,
		targetName = "Standard Door",
		targetIcon = "🚪",
		targetHeight = 2.03,
		category = "Everyday Objects",
		fact = "A standard interior door is about 2.03 meters tall, roughly 7 sheets of A4 paper end to end.",
	},
	{
		referenceName = "Smartphone",
		referenceIcon = "📱",
		referenceHeight = 0.15,
		targetName = "Refrigerator",
		targetIcon = "🧊",
		targetHeight = 1.8,
		category = "Everyday Objects",
		fact = "A typical fridge stands about 1.8 meters tall -- 12 times the length of a smartphone.",
	},
	{
		referenceName = "Coffee Mug",
		referenceIcon = "☕",
		referenceHeight = 0.1,
		targetName = "Upright Piano",
		targetIcon = "🎹",
		targetHeight = 1.3,
		category = "Everyday Objects",
		fact = "An upright piano is about 1.3 meters tall -- 13 times the height of a coffee mug.",
	},
	-- Brainrot: meme characters. Sizes are made-up "lore" heights for fun.
	{
		referenceName = "Tung Tung Tung Sahur",
		referenceIcon = "🪵",
		referenceHeight = 1.5,
		targetName = "Tralalero Tralala",
		targetIcon = "🦈",
		targetHeight = 3.5,
		category = "Brainrot",
		fact = "In meme lore, Tralalero Tralala stands about 3.5 m -- over twice Tung Tung Tung Sahur. (Meme sizes are made up!)",
	},
	{
		referenceName = "Cappuccino Assassino",
		referenceIcon = "☕",
		referenceHeight = 1.2,
		targetName = "Ballerina Cappuccina",
		targetIcon = "🩰",
		targetHeight = 1.8,
		category = "Brainrot",
		fact = "Ballerina Cappuccina is about 1.8 m in lore -- half again as tall as Cappuccino Assassino. (Made-up meme sizes!)",
	},
	{
		referenceName = "Chimpanzini Bananini",
		referenceIcon = "🍌",
		referenceHeight = 2.2,
		targetName = "Brr Brr Patapim",
		targetIcon = "🐒",
		targetHeight = 4,
		category = "Brainrot",
		fact = "Brr Brr Patapim towers at about 4 m in lore -- nearly twice Chimpanzini Bananini. (Made-up meme sizes!)",
	},
	{
		referenceName = "Trippi Troppi",
		referenceIcon = "🦐",
		referenceHeight = 1.1,
		targetName = "Lirili Larila",
		targetIcon = "🌵",
		targetHeight = 5,
		category = "Brainrot",
		fact = "Lirili Larila is about 5 m in lore -- roughly 4.5 Trippi Troppis tall. (Made-up meme sizes!)",
	},
	{
		referenceName = "Verity",
		referenceIcon = "💖",
		referenceHeight = 2.5,
		targetName = "La Vaca Saturno Saturnita",
		targetIcon = "🐄",
		targetHeight = 9,
		category = "Brainrot",
		fact = "La Vaca Saturno Saturnita is a huge 9 m in lore -- about 3.6 Veritys tall. (Made-up meme sizes!)",
	},
	{
		referenceName = "Tung Tung Tung Sahur",
		referenceIcon = "🪵",
		referenceHeight = 1.5,
		targetName = "Bombardiro Crocodilo",
		targetIcon = "🐊",
		targetHeight = 6,
		category = "Brainrot",
		fact = "Bombardiro Crocodilo is about 6 m in lore -- four times Tung Tung Tung Sahur. (Made-up meme sizes!)",
	},
	{
		referenceName = "Verity",
		referenceIcon = "💖",
		referenceHeight = 2.5,
		targetName = "Skibidi Toilet",
		targetIcon = "🚽",
		targetHeight = 1.4,
		category = "Brainrot",
		fact = "Skibidi Toilet is only about 1.4 m in lore -- a bit over half of Verity's height. (Made-up meme sizes!)",
	},
	{
		referenceName = "Trippi Troppi",
		referenceIcon = "🦐",
		referenceHeight = 1.1,
		targetName = "Bombardiro Crocodilo",
		targetIcon = "🐊",
		targetHeight = 6,
		category = "Brainrot",
		fact = "Bombardiro Crocodilo is about 6 m in lore -- over five Trippi Troppis stacked up. (Made-up meme sizes!)",
	},
	{
		referenceName = "Cappuccino Assassino",
		referenceIcon = "☕",
		referenceHeight = 1.2,
		targetName = "Lirili Larila",
		targetIcon = "🌵",
		targetHeight = 5,
		category = "Brainrot",
		fact = "Lirili Larila is about 5 m in lore -- more than four Cappuccino Assassinos. (Made-up meme sizes!)",
	},
	{
		referenceName = "Skibidi Toilet",
		referenceIcon = "🚽",
		referenceHeight = 1.4,
		targetName = "Tralalero Tralala",
		targetIcon = "🦈",
		targetHeight = 3.5,
		category = "Brainrot",
		fact = "Tralalero Tralala is about 3.5 m in lore -- two and a half Skibidi Toilets. (Made-up meme sizes!)",
	},
	{
		referenceName = "Earth",
		referenceIcon = "🌍",
		referenceHeight = 12742000,
		targetName = "Moon",
		targetIcon = "🌕",
		targetHeight = 3474000,
		category = "Space",
		fact = "The Moon's diameter is about 3,474 km, roughly 27% of Earth's 12,742 km diameter.",
	},
	{
		referenceName = "Earth",
		referenceIcon = "🌍",
		referenceHeight = 12742000,
		targetName = "Jupiter",
		targetIcon = "🪐",
		targetHeight = 139820000,
		category = "Space",
		fact = "Jupiter's diameter is about 139,820 km -- around 11 times wider than Earth.",
	},
	{
		referenceName = "Jupiter",
		referenceIcon = "🪐",
		referenceHeight = 139820000,
		targetName = "The Sun",
		targetIcon = "☀️",
		targetHeight = 1391000000,
		category = "Space",
		fact = "The Sun is about 1,391,000 km across -- roughly 10 Jupiters, or 109 Earths, side by side.",
	},
}

return ScaleData
